train_params:
  num_boost_round: 200
  verbose_eval: 10
  early_stopping_rounds: 10

booster_params:
  objective: 'reg:squarederror'
  nthread: -1
  eta: .03
  max_depth: 5

log_params:
  description: 'proba'
  result_path: '../data/result'

#train_cols: ['aged_70_older',
#             'cardiovasc_death_rate',
#             'extreme_poverty',
#             'hospital_beds_per_thousand',
#             'diabetes_prevalence',
#             'positive_rate',
#             'people_fully_vaccinated_per_hundred',
#             'new_deaths_per_million',
#             'total_deaths_per_million',
#             'new_cases_per_million',
#             'total_cases_per_million',
#             'handwashing_facilities']

train_cols: ['aged_70_older',
             'people_fully_vaccinated_per_hundred',
             'new_deaths_per_million']

label_col: 'new_deaths_per_million_tomorrow'
